import "~/styles/globals.css";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";

import {
  ColorSchemeScript,
  DirectionProvider,
  MantineProvider,
} from "@mantine/core";
import { Notifications } from "@mantine/notifications";

import { cookies } from "next/headers";
import App from "~/components/app";
import { cn } from "~/lib/utils";
import { theme } from "~/styles/theme-config";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata = {
  title: "Hadrmoot",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl">
      <head>
        <ColorSchemeScript />
      </head>

      <body className={cn("min-h-screen antialiased")}>
        <DirectionProvider initialDirection="rtl" detectDirection={false}>
          <MantineProvider theme={theme} defaultColorScheme="light">
            <TRPCReactProvider cookies={cookies().toString()}>
              <Notifications limit={3} />
              <App>{children}</App>
            </TRPCReactProvider>
          </MantineProvider>
        </DirectionProvider>
      </body>
    </html>
  );
}
